extends:
  - stylelint-config-standard
ignoreFiles:
  - "**/pagefind/**/*.css"
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - tailwind
        - apply
        - layer
        - screen
        - responsive
        - variants
        - theme
        - utility
        - plugin
        - source
        - custom-variant
  no-descending-specificity: null
  comment-empty-line-before: null
  property-no-vendor-prefix: null
  value-no-vendor-prefix: null
  string-quotes: null
  max-empty-lines: null
  indentation: null
  max-line-length: null
  no-eol-whitespace: null
  declaration-empty-line-before: null
  declaration-colon-newline-after: null
  value-list-comma-newline-after: null
  alpha-value-notation: null
  hue-degree-notation: null
  length-zero-no-unit: null
  custom-property-empty-line-before: null
  at-rule-empty-line-before: null
  declaration-block-no-redundant-longhand-properties: null
  no-duplicate-selectors: null
  color-function-notation: null
