module:
  mounts:
    - source: static
      target: static
    - source: templates
      target: layouts/wowchemycms
outputFormats:
  wowchemycms_config:
    baseName: config
    isPlainText: true
    mediatype: application/yaml
    notAlternative: false
mediaTypes:
  application/yaml:
    suffixes:
      - yml
