name = "Easy Docs"
license = "MIT"
licenselink = "https://github.com/HugoBlox/theme-documentation/blob/main/LICENSE.md"
description = "Easy, all-in-one beautiful documentation website including a customizable homepage and blog. Super fast, empowering you to focus on your content."

homepage = "https://github.com/HugoBlox/theme-documentation"
demosite = "https://hugo-docs-theme.netlify.app"

tags = ["landing", "docs", "blog", "responsive", "minimal", "light", "dark", "multilingual", "dark mode", "tailwind", "company", "gallery"]
features = ["secure", "fast", "search", "dark mode", "widgets"]

# If the theme has a single author
[author]
  name = "George Cushen"
  homepage = "https://georgecushen.com/"
