name: CI - Lint

on:
  push:
    branches: [main]
    paths:
      - "modules/**"
      - "test/**"
      - "scripts/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "biome.json"
      - ".stylelintrc.yaml"
      - "vite.config.js"
  pull_request:
    branches: [main]
    paths:
      - "modules/**"
      - "test/**"
      - "scripts/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "biome.json"
      - ".stylelintrc.yaml"
      - "vite.config.js"

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "22"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: "pnpm"
      - name: Enable Corepack (use pnpm from package.json)
        run: corepack enable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint (Biome + Stylelint)
        run: pnpm run lint
